# Generated by Django 3.0.4 on 2021-01-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20201230_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
